export const POCKET_GET_REQUEST_TOKEN = 'Pocket/GET_GET_REQUEST_TOKEN';
export const POCKET_GET_REQUEST_TOKEN_SUCCESS = 'Pocket/GET_GET_REQUEST_TOKEN_SUCCESS';
export const POCKET_GET_REQUEST_TOKEN_FAILURE = 'Pocket/GET_GET_REQUEST_TOKEN_FAILURE';

export const POCKET_GET_ACCESS_TOKEN = 'Pocket/GET_GET_ACCESS_TOKEN';
export const POCKET_GET_ACCESS_TOKEN_SUCCESS = 'Pocket/GET_GET_ACCESS_TOKEN_SUCCESS';
export const POCKET_GET_ACCESS_TOKEN_FAILURE = 'Pocket/GET_GET_ACCESS_TOKEN_FAILURE';
